version: '3.9'
services:
  nginx:
    image: nginx:1.23.2-alpine
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  wp:
    image: wordpress:6.0.3-php8.1-fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: skiru
      WORDPRESS_DB_PASSWORD: zaq1@WSX
      WORDPRESS_DB_NAME: mateuszkoziol
    user:
      1000:1000
    volumes:
      - .:/var/www/html

  db:
    image: mariadb:10.9.3-jammy
    restart: always
    environment:
      MYSQL_DATABASE: mateuszkoziol
      MYSQL_USER: skiru
      MYSQL_PASSWORD: zaq1@WSX
      MYSQL_RANDOM_ROOT_PASSWORD: '0'
      MYSQL_ROOT_PASSWORD: zaq1@WSX2
    volumes:
      - db:/var/lib/mysql

volumes:
  db: